name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11, 3.12]
    # env:
    #   DBENGINE: django.db.backends.mysql
    #   DATABASE_NAME: computer_workshop
    #   DATABASE_USER: root
    #   DATABASE_PASSWORD: 12345678
    #   DATABASE_HOST: localhost
    #   DATABASE_PORT: 3306
      # DBENGINE: django.db.backends.mysql
      # DATABASE_NAME: ${{ secrets.MYSQL_DBNAME }}
      # DATABASE_USER: ${{ secrets.MYSQL_DBUSER }}
      # DATABASE_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      # DATABASE_HOST: ${{ secrets.MYSQL_DBHOST }}
      # DATABASE_PORT: ${{ secrets.MYSQL_DBPORT }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python core/manage.py test

    - name: Run Migrations
      run: |
        python core/manage.py migrate

